version: "3"
services:
  php:
    image: docker.arvancloud.ir/trafex/php-nginx:3.0.0
    container_name: project101-frontend-serverstatus
    restart: always
    ports:
      - "8083:8080"
    networks:
      - project101network
    environment:
      TZ: Asia/Tehran
      WEBSERVICE_BASE_URL: http://localhost:8080/serverstatus.php
    volumes:
      - type: 'bind'
        source: './code'
        target: '/var/www/html'
      - type: 'bind'
        source: '/etc/localtime'
        target: '/etc/localtime:ro'
      - type: 'bind'
        source: '/etc/timezone'
        target: '/etc/timezone:ro'


networks:
  project101network:
    driver: bridge