version: "3"
services:
  php:
    build: .
    container_name: project101-frontend-guests
    restart: always
    ports:
      - "8082:80"
    networks:
      - project101network
    environment:
      TZ: Asia/Tehran
      WEBSERVICE_BASE_URL: http://localhost:8080
    volumes:
      - type: 'bind'
        source: './code'
        target: '/var/www/html'
      - type: 'bind'
        source: '/etc/localtime'
        target: '/etc/localtime:ro'
      - type: 'bind'
        source: '/etc/timezone'
        target: '/etc/timezone:ro'


networks:
  project101network:
    driver: bridge