version: "3"
services:
  php:
    build: .
    container_name: project101-filemanager-php
    restart: always
    ports:
      - "8081:8080"
    networks:
      - project101network
    environment:
      TZ: Asia/Tehran
      MAX_UPLOAD_SIZE_BYTES: 5000
    volumes:
      - type: 'bind'
        source: project101_filemanager_data
        target: '/home/files'
      - type: 'bind'
        source: './code'
        target: '/var/www/html'
      - type: 'bind'
        source: '/etc/localtime'
        target: '/etc/localtime:ro'
      - type: 'bind'
        source: '/etc/timezone'
        target: '/etc/timezone:ro'


networks:
  project101network:
    driver: bridge